# Generated by Django 5.1.3 on 2026-02-14 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Jonah Western', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=30)),
                ('visibility', models.BooleanField(default=False)),
                ('open_graph_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tags', models.ManyToManyField(to='videos.tag')),
            ],
        ),
    ]
