# Generated by Django 5.1.3 on 2026-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_commentary',
            field=models.BooleanField(default=False),
        ),
    ]
