# Generated by Django 5.1.3 on 2026-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(max_length=50)),
                ('cloudnary_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('weblink_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=30)),
                ('visibility', models.BooleanField(default=False)),
                ('open_graph_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tags', models.ManyToManyField(to='videos.tag')),
            ],
        ),
    ]
