# Generated by Django 5.1.3 on 2026-02-21 07:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_whitelistedemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistedemails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistedemails',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitelistedemails',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
