# Generated by Django 5.1.3 on 2026-02-21 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_whitelistedemails_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistedemails',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
