# Generated by Django 5.1.3 on 2026-02-13 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('external_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=30)),
                ('recent_or_old', models.CharField(choices=[('Recent', 'Recent'), ('Archive', 'Archive')], default='Recent', max_length=50)),
                ('visibility', models.BooleanField(default=False)),
                ('open_graph_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tags', models.ManyToManyField(to='videos.tag')),
            ],
        ),
    ]
