# Generated by Django 5.1.3 on 2026-02-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publication',
            field=models.BooleanField(default=False),
        ),
    ]
