# Generated by Django 5.1.3 on 2026-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='created', max_length=10),
        ),
    ]
